version: "3.9"
volumes:
    db-store:
    redis-store:
services:
  app:
    image: busybox
    depends_on:
      - nginx
      - nuxt
      - laravel
      # - db
      # - minio
      # - redis

  nuxt:
    build: ./nuxt
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./nuxt/app:/usr/src/app
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    tty: true

  laravel:
    build: ./laravel
    volumes:
      - ./laravel/app:/var/www
    command: sh -c 'composer install && php artisan serve --host=0.0.0.0'
    ports:
      - '8000:8000'
    tty: true
    
  nginx:
    build: ./nginx/
    ports:
      - '8080:8080'
    tty: true
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro



    # app:
    #     build: ./docker/app
    #     volumes:
    #         - ./app:/var/www
    # nginx:
    #     image: nginx
    #     container_name: nginx
    #     ports:
    #         - 8080:80
    #     volumes:
    #         - ./app:/var/www
    #         - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # options ==============================================================
    # db:
    #     image: mysql:8.0
    #     ports:
    #         - 33060:3306
    #     volumes:
    #         - db-store:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: password
    #         MYSQL_DATABASE: cobberlt
    #         MYSQL_USER: mysql
    #         MYSQL_PASSWORD: mysql
    #         TZ: 'Asia/Tokyo'
    #     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # redis:
    #     image: "redis:latest"
    #     container_name: redis
    #     ports:
    #         - "6379:6379"
    #     command: redis-server --appendonly yes
    #     volumes:
    #         - redis-store:/data
    # minio:
    #     image: minio/minio:RELEASE.2018-08-25T01-56-38Z
    #     container_name: minio
    #     ports:
    #         - 9000:9000
    #     environment:
    #         MINIO_ACCESS_KEY: minio
    #         MINIO_SECRET_KEY: minio123
    #     command: server /data
    #     volumes:
    #         - ./minio/data:/data
    # mailhog:
    #     image: mailhog/mailhog
    #     ports:
    #         - 8025:8025
