version: "3.9"
volumes:
    db-store:
    redis-store:
services:
  app:
    image: busybox
    depends_on:
      - nginx
      - nuxt
      - laravel
  nuxt:
    build: ./nuxt
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./nuxt/app:/usr/src/app
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    tty: true
  laravel:
    build: ./laravel
    volumes:
      - ./laravel/app:/var/www
    command: sh -c 'composer install && php artisan serve --host=0.0.0.0'
    ports:
      - '8000:8000'
    tty: true
  nginx:
    build: ./nginx/
    ports:
      - '8080:8080'
    tty: true
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
